# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: ruby:2.6

test:
  stage: test
  script:
    - bundle install --with test
    - bundle exec rspec

build:
  stage: build
  script:
    - gem build faastruby.gemspec
  only:
    - tags
  except:
    - branches
    - master

push:
  stage: deploy
  when: manual
  script:
    - gem push faastruby-*.gem
  only:
    - tags
  except:
    - branches
    - master
