#!/usr/bin/env ruby
require 'faastruby'
require 'faastruby/cli'
trap "SIGINT" do
  puts "Exiting"
  exit 130
end
if ARGV[0] == '--region'
  ARGV.shift
  ENV['FAASTRUBY_REGION'] = ARGV.shift
end
command = ARGV.shift
FaaStRuby::CLI.run(command, ARGV)
